server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/venzersiz/learn-spring-cloud-gateway-config-server-git
          default-label: main
          clone-on-start: true
          # 비공개 저장소인 경우
          # username: ${CONFIG_SERVER_GIT_USERNAME:}
          # password: ${CONFIG_SERVER_GIT_PASSWORD:}
